---
- name: Create CA key directory
  file:
    path: "{{ certificates_ca_key_dir }}"
    state: directory
  delegate_to: "{{ certificates_ca_server }}"

- name: Copy openssl server/ca extensions
  copy:
    src: "{{item}}"
    dest: "{{ certificates_ca_key_dir }}"
    owner: root
    group: root
    mode: 0400
  with_items:
    - openssl-ca.ext
    - openssl-client.ext
  delegate_to: "{{ certificates_ca_server }}"

- name: Generate CA key
  command: openssl req -nodes -newkey rsa:{{ certificates_key_length }} -keyout ca-key.pem -out ca-csr.pem -days {{ certificates_ca_days_valid }} -{{ certificates_ca_digest }} -subj /CN={{ certificates_ca_common_name }}/
  args:
    chdir: "{{ certificates_ca_key_dir }}"
    creates: ca-key.pem
  delegate_to: "{{ certificates_ca_server }}"

- name: Protect CA key
  file:
    path: "{{ certificates_ca_key_dir }}"
    mode: 0400
  delegate_to: "{{ certificates_ca_server }}"

- name: Sign CA key
  command: openssl x509 -req -in ca-csr.pem -out ca.crt -CAcreateserial -signkey ca-key.pem -{{ certificates_ca_digest }} -days {{ certificates_ca_days_valid }} -extfile openssl-ca.ext
  args:
    chdir: "{{ certificates_ca_key_dir }}"
    creates: ca.crt
  delegate_to: "{{ certificates_ca_server }}"

- name: Install ca.conf config file
  template:
    src: ca.conf.j2
    dest: "{{ certificates_ca_key_dir }}/ca.conf"
    owner: root
    group: root
    mode: 0744
  delegate_to: "{{ certificates_ca_server }}"

- name: Create initial certificate revocation list squence number
  shell: "echo 00 > crl_number"
  args:
    chdir: "{{certificates_ca_key_dir}}"
    creates: crl_number
  delegate_to: "{{ certificates_ca_server }}"

- name: Install revocation script
  template:
    src: revoke.sh.j2
    dest: "{{certificates_ca_key_dir}}/revoke.sh"
    owner: root
    group: root
    mode: 0755
  delegate_to: "{{ certificates_ca_server }}"

- name: Ensure certificate revocation list database exists
  file:
    path: "{{certificates_ca_key_dir}}/index.txt"
    state: touch
  delegate_to: "{{ certificates_ca_server }}"

- name: Set up certificate revocation list
  command: sh revoke.sh
  args:
    chdir: "{{ certificates_ca_key_dir }}"
    creates: "{{ certificates_ca_key_dir }}/ca-crl.pem"
  delegate_to: "{{ certificates_ca_server }}"
