---
- name: Check if ca public key is present
  stat: "{{ certificate_local_ca_path }}"
  register: ca_certificate_present

- name: Check if a certificate is present
  stat: "{{ certificate_path }}"
  register: local_certificate

- name: Check if certificate is expired
  openssl_certificate:
    path: "{{ certificate_path }}"
    provider: assertonly
    valid_in: 1209600
  when: local_certificate.stat.exists
  register: local_certificate_stats

- name: Get CA certificate
  include: get_ca_certificate.yml
  when: not ca_certificate_present.stat.exists

- name: Debug
  debug:
    var: local_certificate_stats

- name: Get new certificate
  include: get_new_certificate.yml
  when: not ca_certificate_present.stat.exists or local_certificate_stats



